### PR TITLE
Conditional inside conditional

### PR DESCRIPTION
**Pull request by Rubenicos**
Before:
```yaml
actions:
  all:
    - 'tell: &bNormal Action'
    # [ Conditional Action ]
    # Only allow normal actions
    - condition: 'perm *permission.123'
      actions:
        - 'tell: &aYES'
      deny:
        - 'tell: &cNO'
```

After:
```yaml
actions:
  all:
    - 'tell: &bNormal Action'
    # [ Conditional Action ]
    # Allow more conditional actions inside infinitely
    - condition: 'perm *permission.123'
      actions:
        - 'tell: &aYES'
        - condition: 'perm *other.permission'
          actions:
            - 'tell: &aYEP'
          deny:
            - 'tell: &cNOPE'
      deny:
        - 'tell: &cNO'
```

### CODE REVIEW

**Comment by 157946a** [comment]
This may help you

actions:
      all:
        - condition: 'perm *permission.123'
          actions:
            - 'tell: Prize 1'
          deny:
            - 'tell: No permission permission.123'
            - 'return'
        - condition: 'perm *other.permission'
          actions:
            - 'tell: Prize 2'
          deny:
            - 'tell: No permission other.permission'
            - 'return'
        - condition: 'perm *not.permission'
          actions:
            - 'tell: Prize 3'
          deny:
            - 'tell: No permission not.permission'
            - 'return'

**Comment by Rubenicos** [comment]
> This may help you
> 
> https://paste.helpch.at/eyiqiradop.pl
> 
> You can try it, first give permission.123 and then other.permission permission, and then the other way around, give other.permission first and then permission.123 permission

It doesn't work if I try to make prize sets separated by conditional categories

**Comment by Score2** [comment]
Part of the changes in this PR led to this issue:
https://github.com/InsinuateProjects/TrMenu/issues/108

**Comment by Score2** [comment]
But I didn't have time to solve this problem, so I decided to restore it. If you solve this problem, you can initiate a new PR.:)

**Comment by 157946a** [comment]
https://github.com/InsinuateProjects/TrMenu/issues/109
Your function has a problem again, which causes the return|break function to fail, and you need to fix it again

**Comment by 157946a** [comment]
Your new function caused the task function to fail. The pro test is indeed the case. To be honest, the writing method I said is the function you want, but the writing position is different.

**Comment by 157946a** [comment]
Did you see it?

**Comment by Score2** [comment]
> Your new function caused the task function to fail. The pro test is indeed the case. To be honest, the writing method I said is the function you want, but the writing position is different.

I don't think task has anything to do with conditional.

**Pull request merged**
